services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: news_feed_bot
      PGDATA: /var/lib/postgresql/data/
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data/

  app:
    build:
      context: .
    restart: on-failure
    depends_on:
      - db

volumes:
  db: